### ISSUE TITLE
Any financial way to support to project?

### ISSUE THREAD

**Issue by xcom169** [OpenSAGE/OpenSAGE#118]
If someone can't help with new lines of code, is there any financial way to help?

**Comment by paavohuhtala** [comment]
Not right now - and this is just my take on this - but I think it's very unlikely we'll accept any money any time soon.

All 3 of us in the core team are either employed, studying full-time or both. Money can be a motivator, but at least in my case the biggest bottleneck to productivity is time. I think it's very unlikely where I'd earn enough to actually make working on the project regularly worth it (from a purely selfish financial point of view) compared to my normal job. Plus all of us do this as a hobby; to relax from the other stuff.

There's also the fact that taking donations might attract unwanted attention from EA. OpenSAGE is strictly non-commercial, and from my point of view accepting optional donations wouldn't compromise that, but it's possible EA's lawyers would disagree.

However, there are some more indirect donations I could see us accepting in the future:
* Cloud provider credits or VM instances, in order to host a community website, a matchmaking server or dedicated build / continuous integration services.
* Domain name(s)
* Artists and visual designers who want to support us could help with web design and contribute logos, icons and other such assets. None of us a experts at that sort of stuff 😄

**Comment by Dedale2** [comment]
I hope i am not wasting your time or breaking etiquette by writing this here but let me thank you for doing this and adding Linux support. It seems a huge undertaking. I hope you succeed and get the kind of help you need.  

As a Linux player who appreciated this game i no longer play, i am delighted. :)

Your project has been mentioned on the GaminOnLinux website and the news was well received. :)

**Comment by MetaIdea** [comment]
People can donate to Tim Jones, the initiator, head and main contributor of this project via Patreon: https://www.patreon.com/tgjones
He does some other great projects like Shader Playground as well.

**Comment by tgjones** [comment]
@MetaIdea thanks for the compliment :) However, I wouldn't want people to make a connection between my Patreon and OpenSAGE, primarily because there are several developers apart from me who contribute a lot to OpenSAGE, and we don't have a system in place to fairly distribute donations.

Also, as @paavohuhtala mentioned above, the whole idea of donations is a grey area from the legal point of view.

Apart from those reasons, I work on OpenSAGE purely for fun, and I'd prefer not to feel obligated to deliver anything on any kind of schedule...
