### ISSUE TITLE
"Standalone" DDS loader library

### ISSUE THREAD

**Issue by mellinoe** [OpenSAGE/OpenSAGE#139]
Hey guys,

I'm messing around with the [Amazon Bistro](https://developer.nvidia.com/orca/amazon-lumberyard-bistro) scene that's free to use from Nvidia. The textures are all DDS files, and the loader that OpenSAGE has seems to work quite well. Is there any interest in separating out the DDS loader into a standalone library / nuget package? At the moment, I am compiling a forked copy of the code, which pulls in quite a few helper classes and types. The Bistro scene uses BC5 pixel format (or "ATI2" in DDS parlance), which I've added to Veldrid 4.4.0 and to my forked version of the DDS loader. I will make a pull request with those fixes back to the repository here (assuming you guys are okay with updating to 4.4.0 once it's stable), but it would be great (at least long-term) to have just a single version of the code here.

Thoughts?

**Comment by tgjones** [comment]
It’s definitely something I’ve thought about. But I was under the impression that Pfim is (now) basically what you’re looking for, since it got support for not-decompressing during load. I think you know about Pfim, so is there some reason that it didn’t work for you?

I originally did plan to separate my DDS loader out into a separate NuGet package, but @feliwir persuaded me not to indulge in NIH, so we are considering using Pfim ourselves.

**Comment by tgjones** [comment]
@mellinoe just checking in on this - did you try adding BC5 support to Pfim?

**Comment by mellinoe** [comment]
I haven't checked back in on it, but it should be supported now: https://github.com/nickbabcock/Pfim/issues/23

**Comment by tgjones** [comment]
Cool - I’ll close this in favour of Pfim then. We have our own TODO to replace our custom DDS parser with Pfim.
