### ISSUE TITLE
How to build OpenSage.LowLevel without removing xamarinmac20 from targets?

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#17]
Self-explanatory title. I couldn't build the graphics DLL on Windows 10 without removing `xamarinmac20` from `<TargetFrameworks>` in the .csproj. Do I need to install the Xamarin SDK or do something else to fix this properly? 🤔

I'm the running the latest VS Enterprise with all recent .NET targeting packs installed.

**Comment by tgjones** [comment]
If you (somewhat unintuitively) choose the "Mobile development with .NET" workload in the Visual Studio Installer, you'll be able to build the `xamarinmac20` target.

I can do some MSBuild trickery to exclude this target when building on Windows, but it's quite handy for my own development (on Windows) to keep it in, since it lets me see errors from both the D3D11 and Metal backends without even having to compile.

The ideal would be an MSBuild conditional thing to skip the `xamarinmac20` target only if the Xamarin workload isn't installed. I'll look into that.

**Comment by paavohuhtala** [comment]
Thanks! I installed the Xamarin component from the VS installer and it now builds with an unmodified csproj.

There's still a build warning 

> No Address and User has been specified in order to establish a connection to a Mac Server, so only the main assembly was compiled for project 'OpenSage.LowLevel'. Connect to a Mac Server and try again to build the full application.

but it doesn't prevent it from building.

Maybe this should be added to the readme?

**Comment by tgjones** [comment]
Fixed this by removing xamarinmac20 altogether...
