### ISSUE TITLE
Use config file to define game data

### ISSUE THREAD

**Issue by cookgreen** [OpenSAGE/OpenSAGE#225]
Hello, I know this project by OpenRA, this is a wonderful project, and seems like that it lack of config file to define game data like OpenRA.
OpenRA use yaml format to define the data in game, so that it can modify the data dynamically without re-building the game engine, I don't think everything use hardcode is a good idea.
Of course, this project is a new project, not like OpenRA developed in many years, so hope you guys can like this suggestion.
Good Luck!

**Comment by paavohuhtala** [comment]
I think you might be mistaken. OpenSAGE, unlike OpenRA, is based on the idea of loading assets (data and configuration) from the original unmodified files of SAGE games. The games have literally thousands of INI and XML files, and I think it's not far off to say that **most** of the source code in OpenSAGE is for loading config files. 😉 

We don't have much game data of our own (none at the moment, in fact), and pretty much everything currently hardcoded is only like that because we aren't using all the config options. The only thing I'll see us adding in the future is a load order config file so that users can load game data (= mods) from files other than the installation folder.

**Comment by cookgreen** [comment]
okay, maybe you're right
