### ISSUE TITLE
Will this project merged with OpenRA?

### ISSUE THREAD

**Issue by sycspysycspy** [OpenSAGE/OpenSAGE#511]
Just asking, since it's a very similar project and OpenRA has a fairly large community. If OpenSAGE could be part of OpenRA it would be nice.

**Comment by feliwir** [comment]
Hello @sycspysycspy 

Eventhough the goals of OpenRA and OpenSAGE are very similar, the technology behind the games unfortunaly isn't. While OpenRA is reimplementing the early C&C games (which were mostly 2D), OpenSAGE is trying to reimplement the SAGE (Strategy Action Game Engine), which was used by later C&C titles, but also by other franchises like BFME. The task of reimplementing an entire 3D engine is already a large undertaking, which takes several years of work.

Since the technical differences between the early C&C games and the later games is so huge, there is not much code that could be shared, so it wouldn't make much sense / have any benefit to merge those to projects. 
However we (OpenSage) are in contact with OpenRA people (namely @pchote) to ask for advice every now and learn from their approach.
