### ISSUE TITLE
Pace of development

### ISSUE THREAD

**Issue by cbordeman** [OpenSAGE/OpenSAGE#672]
Are we still pretending this project hasn't been on life support the last 3 years?

**Comment by feliwir** [comment]
You realize this project is a hobby project of a few people? We can develop at whatever pace we like, since we don’t owe anyone anything. 

I find it quite rude to complain about other people not spending enough of their freetime if i never contributed anything but comments like these.

Feel free to speedup development by contributing yourself.

**Comment by cbordeman** [comment]
Yeah except I asked about the apparent slow progress about a year ago and was very rudely rebuffed, claiming it was moving rapidly.  I was wondering whether I should help considering the existing participants didn't seem serious about completing it in the next decade.  Three years ago I even tried to bring up the networking implementation and there was very intense bullying by one team member on Discord, who posted literally a thousand messages in 2 hours to try to drown out all other viewpoints.  Since then, he's made zero implementation effort on that.  I look at all the PRs that have been open since February and it seems clear the owner of the repo isn't even serious about reviewing those.  All this taken together makes it hard to decide to contribute.
