### ISSUE TITLE
Generals: When placing a scaffold and then right-clicking to cancel, particle effects remain

### ISSUE THREAD

**Issue by charliefoxtwo** [OpenSAGE/OpenSAGE#686]
The lower fire is from a canceled barracks, and the upper smoke stack is from a canceled power plant.

Note that construction did not begin for the object so this isn't a die call.

![image](https://user-images.githubusercontent.com/30303272/200146028-70c7b44b-8339-4c7a-a2c6-0a4e6ac9364a.png)

In Generals/ZH, the particle effects don't even appear until the object is fully constructed, so we probably just shouldn't be showing these in the ghost or before construction is complete

**Comment by c001ac1d** [comment]
hello. here's what i found on this one
https://github.com/OpenSAGE/OpenSAGE/blob/f3f8364885eaccd1c89c3d5f675a0a8b6f4861cb/src/OpenSage.Game/Logic/OrderGeneratorInputHandler.cs#L72-L75

which then calls
https://github.com/OpenSAGE/OpenSAGE/blob/f3f8364885eaccd1c89c3d5f675a0a8b6f4861cb/src/OpenSage.Game/Logic/OrderGeneratorSystem.cs#L182-L185

which disposes the previous ActiveGenerator (was an instance of `ConstructBuildingOrderGenerator`)
https://github.com/OpenSAGE/OpenSAGE/blob/f3f8364885eaccd1c89c3d5f675a0a8b6f4861cb/src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs#L162-L167

which disposes the `_previewObject`
https://github.com/OpenSAGE/OpenSAGE/blob/f3f8364885eaccd1c89c3d5f675a0a8b6f4861cb/src/OpenSage.Game/Logic/Object/GameObject.cs#L1760-L1765

which calls
https://github.com/OpenSAGE/OpenSAGE/blob/f3f8364885eaccd1c89c3d5f675a0a8b6f4861cb/src/OpenSage.Game/Client/GameClient.cs#L52-L59

however, this is where the call stack stops, because `Drawable` doesn't implement a proper `Dispose` method that cleans up its `DrawModule`s, which doesn't cleanup the `W3dModelDraw`, thus not cleaning up the particle systems

**Comment by c001ac1d** [comment]
i've created #905 to fix the particle leaking issue.


regarding this:
> In Generals/ZH, the particle effects don't even appear until the object is fully constructed, so we probably just shouldn't be showing these in the ghost or before construction is complete

perhaps it may be better to move this into its own issue? if you don't think so, i'd also like to create a PR that prevents particles from appearing on preview objects

**Comment by charliefoxtwo** [comment]
> perhaps it may be better to move this into its own issue? anyways, I'd also like to create a PR that prevents particles from appearing on preview objects, if you approve this change of course

Yeah, that would be great! A separate issue/PR makes sense for sure.

**Comment by charliefoxtwo** [comment]
https://github.com/OpenSAGE/OpenSAGE/issues/906 created
