### ISSUE TITLE
Emperor: Battle for Dune support?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [OpenSAGE/OpenSAGE#76]
Hello.

I am just wondering if you guys plan on adding Emperor Battle for Dune game to this as well? I read up on W3D and Sage 1 and I seen that both actually used the same rendering techniques, plus that game could use a good remaster, too.

**Comment by paavohuhtala** [comment]
My opinion:

I think it's highly unlikely because - as you said - it doesn't use SAGE. While the renderer is apparently quite similar, it's a relatively small part of the engine. It doesn't have an official mod SDK either, which would make reverse engineering significantly more difficult.

We have some modules which could be useful for a different remake project, but that's a job for a different team.

**Comment by tgjones** [comment]
It's definitely an interesting suggestion - thanks for asking about it. But as @paavohuhtala said, it doesn't use SAGE, so it wouldn't have as much in common with SAGE games as SAGE games have in common with each other. So it's not likely we'd implement it.
