### ISSUE TITLE
Question: Location of game settings and control options ?

### ISSUE THREAD

**Issue by Zexaron** [OpenSAGE/OpenSAGE#79]
Hey

I was wondering, hopefully not too early, ofcourse no conclusion has to be done at this time and this could stay open to future suggestions from other people.

I personally would have it only in launcher, also avoids the restart issues, not having to bother the user with dialog, and not having to implement a restart too, change options and run cleanly imo makes it simpler and less prone to weird circumstances.

Secondary if in launcher, would it be global, or per-game, so you would have tabs.

Unless some of you guys are big on max authenticity of the original, I understand.

**Comment by tgjones** [comment]
We haven't implemented loading or saving options yet, so it's hard to be sure how any of it will work. That said, I am imagining each game will continue to have its own options. I prefer OpenRA's model where each "mod" (game) is an almost entirely separate thing - it makes things easier for us, and I think easier for mod developers too.

Closing this because there's not really anything we can do at this stage, but I'd be glad of further comments from anybody who has an opinion about this.
