### ISSUE TITLE
Re-Interpretation layer when parsing official game data ?

### ISSUE THREAD

**Issue by ghost** [OpenSAGE/OpenSAGE#87]
Has there been any talk or thought about such a system, to make it more easily manageable?

For example, the original engine would parse INI's case sensetive, if you created a command button reference on the control bar with "`Airf_AmericaVehicle...`" instead of "`AirF_AmericaVehicle...`" it would work but as soon as the user would hover the mouse over the button the game engine would freeze.

Or such thing would be put directly to the implementation? I just think it makes it more clear if it's put in a specific structre in the code, so you have it more or less in one place.

By re-interpretation I mean, that what you put into INI's is interpreted differently than by the original engine, but in a way that you can do more weird things in the INIs but it would still work, maybe better name for this is "parse robustness", maybe this could be done in the INI parser, I'm just wondering, if this would be nice for other things, not just INIs, more of a vague idea.

**Comment by paavohuhtala** [comment]
Sorry, but I'm not exactly sure what you're proposing here. A setting for the INI parser to ignore case? A general-purpose transformation system for INI files?

Your example in particular could be solved by throwing an exception or logging a warning from the UI system if there's a command button with an invalid reference. It would likely be just a few lines of simple code instead of a larger general purpose system.

**Comment by Zexaron** [comment]
Yeah it may not be an actual code system, but maybe a reference file containing such cases, just to have a handy list.

The more bigger point what I was getting at is that with a new engine it will be difficult to get the behavior of things exactly as it was in the original engine, so in terms of values, the values are built to the original engine physics and stuff, maybe this new engine would like to do things more efficiently (performance) and more correct in some ways, but still preserving original behavior, but you would have to adjust raw values if in some cases you would be using different SI unit types, or just more accurate.

This would avoid changing the INI files and it's values, if you read some value and the number is "`210`" degrees from an INI, that would be re-interpreted as "`150`" degrees and that's what the value would show up in memory, debug etc, if for some reason fundamentals are different in this engine, but this might be a bad example.

**Comment by feliwir** [comment]
I am not sure what would be the benefit of such a system. The purpose of this project is to behave like the original game, so the values from the INI files should be interpreted correctly, otherwise it’s a bug. Since the engine is designed to behave line the original engine i don’t think this should be the goal, not fixing wrong interpretations afterwards.

**Comment by Zexaron** [comment]
Allright, maybe the use could be in modding, or more specifically, a remastered version (which would technically be a unofficial/separate mod anyway) 

I have a number of ideas regarding that, but now that I found about the discord channel, I'll ask and discuss there first to get an idea of what kind of stance you guys have regarding that.
