### ISSUE TITLE
Zero Hour: Experience Window background not rendering

### ISSUE THREAD

**Issue by charliefoxtwo** [OpenSAGE/OpenSAGE#907]
### Actual
The zero hour experience window just isn't drawing at all for some reason. It looks like Zero Hour uses images for the background here, and for the life of me I can't figure out why the image isn't appearing. Everything seems to be correct, the image is present in the window and the call is being made to draw it, but nothing seems to appear.
![image](https://github.com/OpenSAGE/OpenSAGE/assets/30303272/f6951c09-c281-43e0-b7d5-00cdcbec0204)

**Comment by c001ac1d** [comment]
MAN was this hard to debug. i was legit starting to think there was a bug in veldrid or something.

in this comment i've referenced that there may be a problem with pixel copying in `MappedImageUtility::CreateTexture`:
https://github.com/OpenSAGE/OpenSAGE/issues/862#issuecomment-2136175779

but if this was the case for the entire UI, we wouldn't see much on the screen, right?
so i thought, maybe the texture itself is problematic? maybe we're not reading some kind of flag and not applying needed attributes to the created texture and what not?
as it turned out, we're not rendering much DDS stuff in the UI (in fact, i think we didn't render any DDSs in the UI at all before this problem). all of the UI images are TGAs, and our rendering libraries eat TGAs for breakfast.
i took a little read on the pixel format used by this particular texture (the experience menu background). the texture uses DXT5 block compression. its native pixel format is BC3_UNorm. the data remains compressed even after the texture is created and uploaded to the GPU. so maybe we're just not copying compressed data correctly?
here's what i have so far:

1. turns out the destination texture that we're copying into should be of the same BC3_UNorm format as the source
2. i've read that each compressed block in DXT5 is 16 bytes in size, so i tried offsetting the texture by *blocks*, not by pixels
3. i've also read that block compressed textures (or DDS in general) don't like to be the size which is not divisible by 4. that is, width and height dimensions should be divisble by 4 for these textures to work properly

made a small test to prove above points. in `MappedImageUtility::CreateTexture`:
```csharp
            var width = (uint)src.Width;
            var height = (uint)src.Height;
            var top = (uint)src.Top;
            var left = (uint)src.Left;

            var format = mappedImage.Texture.Value.Texture.Format;

            switch(format)
            {
            // should probably get the block size data from the DdsFile class somehow + support other compressed formats later
            case PixelFormat.BC3_UNorm:
                width = (width + 3) / 4 * 4;
                height = (height + 3) / 4 * 4;
                top *= 16;
                left *= 16;

                break;
            }
            
            var imageTexture = graphicsDevice.ResourceFactory.CreateTexture(
                TextureDescription.Texture2D(
                    width,
                    height,
                    1,
                    1,
                    format, // consistency in pixel formats between source and destination textures
                    TextureUsage.Sampled
                )
            );
```
...
```csharp
            commandList.CopyTexture(
                mappedImage.Texture.Value, left, top, 0, 0, 0,      // Source
                imageTexture, 0, 0, 0, 0, 0,                        // Destination
                width, height, 1, 1
            ); 
```

**Comment by c001ac1d** [comment]
as you can see there's still something a little of with the window in terms of positioning, im trying to figure out what that is, but for now i'm happy that i'm on the right path to solution

**Comment by c001ac1d** [comment]
this made the result a little better
```csharp
            switch(format)
            {
                case PixelFormat.BC3_UNorm:
                    top *= 4;
                    left *= 4;
                    width = (width + 3) / 4 * 4;
                    height = (height + 3) / 4 * 4;

                    break;
            }
```
![image](https://github.com/OpenSAGE/OpenSAGE/assets/147560985/9e92f1d2-153c-4c52-90f7-2f03fceadfa9)

still i don't entirely understand the math behind this, right now it feels like i'm poking a black box with a stick and observing how it reacts
need to investigate further

**Comment by c001ac1d** [comment]
> any chance top should just be 0 in this case?

yes, i thought of that
i think we should fix this value to be the nearest divisible by 4, e.g. for 1 it will be 0, and for 3 it will be 4

also, i've said earlier that
> each compressed block in DXT5 is 16 bytes in size, so i tried offsetting the texture by blocks, not by pixels

this is true, however the block size in bytes is irrelevant for us. because we're offseting by A NUMBER OF BLOCKS, not by BYTES
the amount of blocks in a texture is calculated like this:
`numVerticalBlocks = height / 4`
`numHorizontalBlocks = width / 4`
with that in mind, it actually makes sense why the following code kinda worked well
```csharp
switch(format)
            {
                case PixelFormat.BC3_UNorm:
                    top *= 4;
                    left *= 4;
                    width = (width + 3) / 4 * 4;
                    height = (height + 3) / 4 * 4;

                    break;
            }
```
 we're offseting `top` and `left` by 1 block (1 * 4 = 4), and we're making width and height divisible by 4. all of these dimensions are still kept as pixels, but because of our multiplications, the renderer knows how to transform these pixel values into block values. so it does the following:
 ```
top_blocks = top / 4
left_blocks = left / 4
width_blocks = width / 4
height_blocks = height / 4
```
and then it accesses the pixel data using this information

**Comment by c001ac1d** [comment]
> we should fix this value to be the nearest divisible by 4, e.g. for 1 it will be 0, and for 3 it will be 4
maybe we'll use the same method for width and height

**Comment by c001ac1d** [comment]
i'll try to write a fix of this issue now, cuz i think i have a fine enough grasp of the cause

**Comment by c001ac1d** [comment]
@charliefoxtwo check #909 out
